const fileInput = document.getElementById("fileInput");
const fileName = document.getElementById("nombre-archivo");
const content = document.getElementById("content");

const impactTranslations = {
    en: {
        back: "Back to 3ntropy",
        subtitle: "Cumulative impact of detected differences between declared and observed infrastructure.",
        loadTitle: "Load detection log",
        loadBefore: "Upload",
        loadAfter: "generated by the MCP server whenever",
        loadAfterAfter: "detects drift.",
        selectFile: "Select file",
        noFile: "No file selected",
        noFileTitle: "JSONL format only",
        empty: "Waiting for a detection log to analyze.",
        invalid: "The file does not contain valid entries.",
        detections: "Runs with detected drift",
        differences: "Total differences found",
        highRisk: "High-risk findings",
        timeSaved: "Estimated time saved",
        chartTitle: "Time saved per run (latest 10)",
        chartSubtitle: "Distribution of time saved per inspection cycle",
        historyTitle: "Detection history",
        historySubtitle: "Detailed chronological record of drift events",
        date: "Date",
        diffs: "Diffs",
        risk: "Risk",
        time: "Time saved",
        highRiskBadge: "high risk",
        noHighRisk: "no high risk",
        minutes: "min",
        cardTitleScans: "Active scans",
        cardTitleDiffs: "Discrepancies",
        cardTitleRisk: "Critical severity",
        cardTitleTime: "Operational efficiency",
    },
    es: {
        back: "Volver a 3ntropy",
        subtitle: "Impacto acumulado de las diferencias detectadas entre la infraestructura declarada y observada.",
        loadTitle: "Cargar registro de detecciones",
        loadBefore: "Sube",
        loadAfter: "generado por el servidor MCP cada vez que",
        loadAfterAfter: "detecta drift.",
        selectFile: "Seleccionar archivo",
        noFile: "Ningún archivo seleccionado",
        noFileTitle: "Formato JSONL soportado",
        empty: "A la espera de un registro de detecciones para analizar.",
        invalid: "El archivo no contiene entradas válidas.",
        detections: "Corridas con drift detectado",
        differences: "Diferencias totales encontradas",
        highRisk: "Hallazgos de alto riesgo",
        timeSaved: "Tiempo estimado ahorrado",
        chartTitle: "Tiempo ahorrado por corrida (últimas 10)",
        chartSubtitle: "Distribución de tiempo rescatado por cada ciclo de inspección",
        historyTitle: "Historial de detecciones",
        historySubtitle: "Registro cronológico detallado de eventos de drift",
        date: "Fecha",
        diffs: "Diffs",
        risk: "Riesgo",
        time: "Tiempo ahorrado",
        highRiskBadge: "de alto riesgo",
        noHighRisk: "sin riesgo alto",
        minutes: "min",
        cardTitleScans: "Escaneos activos",
        cardTitleDiffs: "Discrepancias",
        cardTitleRisk: "Severidad crítica",
        cardTitleTime: "Eficiencia operativa",
    }
};

let currentEntries = [];
let currentLanguage = localStorage.getItem("3ntropy-language") ||
    (navigator.language?.toLowerCase().startsWith("es") ? "es" : "en");

function dictionary() {
    return impactTranslations[currentLanguage] || impactTranslations.en;
}

function applyImpactLanguage(language) {
    currentLanguage = impactTranslations[language] ? language : "en";
    const text = dictionary();
    document.documentElement.lang = currentLanguage;
    document.querySelectorAll("[data-impact-i18n]").forEach((element) => {
        const value = text[element.dataset.impactI18n];
        if (value) element.textContent = value;
    });
    document.querySelectorAll("[data-impact-language]").forEach((button) => {
        const active = button.dataset.impactLanguage === currentLanguage;
        button.classList.toggle("active", active);
        button.setAttribute("aria-pressed", String(active));
    });
    localStorage.setItem("3ntropy-language", currentLanguage);
    if (currentEntries.length > 0) render(currentEntries);
}

document.querySelectorAll("[data-impact-language]").forEach((button) => {
    button.addEventListener("click", () => applyImpactLanguage(button.dataset.impactLanguage));
});

applyImpactLanguage(currentLanguage);

fileInput.addEventListener("change", async (event) => {
    const file = event.target.files[0];
    if (!file) return;
    fileName.textContent = file.name;
    const rawText = await file.text();
    currentEntries = rawText
        .split("\n")
        .map((line) => line.trim())
        .filter(Boolean)
        .map((line) => {
            try {
                return JSON.parse(line);
            } catch {
                return null;
            }
        })
        .filter(Boolean);

    render(currentEntries);
});

function render(entries) {
    const text = dictionary();
    const locale = currentLanguage === "es" ? "es-BO" : "en-US";

    if (entries.length === 0) {
        content.replaceChildren(createEmptyState(text.invalid));
        return;
    }

    const totalDetections = entries.length;
    const totalDiffs = entries.reduce((sum, entry) => sum + (entry.total_diffs || 0), 0);
    const totalHighRisk = entries.reduce((sum, entry) => sum + (entry.high_risk_diffs || 0), 0);
    const totalMinutes = entries.reduce((sum, entry) => sum + (entry.estimated_minutes_saved || 0), 0);
    const totalHours = Math.round((totalMinutes / 60) * 10) / 10;
    const maxMinutes = Math.max(...entries.map((entry) => entry.estimated_minutes_saved || 0), 1);

    const cards = document.createElement("div");
    cards.className = "cards";
    cards.append(
        createMetricCard(text.cardTitleScans, totalDetections, text.detections, "scans"),
        createMetricCard(text.cardTitleDiffs, totalDiffs, text.differences, "discrepancy"),
        createMetricCard(text.cardTitleRisk, totalHighRisk, text.highRisk, "severity", "var(--high)"),
        createMetricCard(text.cardTitleTime, `${totalHours}h`, text.timeSaved, "eficiency", "var(--low)")
    );

    const chartPanel = createPanel(text.chartTitle, text.chartSubtitle);
    entries.slice(-10).forEach((entry) => {
        const percentage = Math.max(4, Math.round(((entry.estimated_minutes_saved || 0) / maxMinutes) * 100));
        const date = new Date(entry.timestamp);
        const label = Number.isNaN(date.valueOf()) ? String(entry.timestamp) : date.toLocaleTimeString(locale);
        chartPanel.append(createBar(label, percentage, `${entry.estimated_minutes_saved || 0} ${text.minutes}`));
    });

    const historyPanel = createPanel(text.historyTitle, text.historySubtitle);
    const table = document.createElement("table");
    const header = document.createElement("thead");
    const headerRow = document.createElement("tr");
    [text.date, text.diffs, text.risk, text.time].forEach((label) => {
        const cell = document.createElement("th");
        cell.textContent = label;
        headerRow.append(cell);
    });
    header.append(headerRow);
    table.append(header);

    const body = document.createElement("tbody");
    entries.slice().reverse().forEach((entry) => {
        const date = new Date(entry.timestamp);
        const dateLabel = Number.isNaN(date.valueOf()) ? String(entry.timestamp) : date.toLocaleString(locale);
        const row = document.createElement("tr");
        row.append(
            createCell(dateLabel),
            createCell(entry.total_diffs || 0),
            createRiskCell(entry.high_risk_diffs || 0, text),
            createCell(`${entry.estimated_minutes_saved || 0} ${text.minutes}`)
        );
        body.append(row);
    });
    table.append(body);
    historyPanel.append(table);

    content.replaceChildren(cards, chartPanel, historyPanel);
}

function createEmptyState(message) {
    const element = document.createElement("div");
    element.className = "empty";
    element.textContent = message;
    return element;
}

function createMetricCard(title, value, label, extraClass, color) {
    const card = document.createElement("div");
    card.className = `card ${extraClass}`;
    
    const colorStyle = color ? `style="color: ${color};"` : "";

    card.innerHTML = `
        <div class="card-bg-glow-${extraClass}"></div>
        <div class="card-header">
            <span class="card-title" ${colorStyle}>${title}</span>
            <span class="card-icon">I</span>
        </div>
        <div class="card-data">
            <div class="value" ${colorStyle}>
                ${value}
            </div>
            <div class="label">
                ${label}
            </div>
        </div>
    `;
    
    return card;
}

function createPanel(title, subtitle) {
    const panel = document.createElement("div");
    panel.className = "panel";
    
    panel.innerHTML = `
        <h2>${title}</h2>
        <p class="panel-subtitle">${subtitle}</p>
        <br/>
        <hr/>
        <br/>
    `;
    
    return panel;
}

function createBar(label, percentage, value) {
    const row = document.createElement("div");
    row.className = "bar-row";
    
    row.innerHTML = `
        <div class="bar-label">${label}</div>
        <div class="bar-track">
            <div class="bar-fill" style="width: ${percentage}%; border-radius: 999px;"></div>
        </div>
        <div class="bar-value">${value}</div>
    `;
    
    return row;
}

function createCell(value) {
    const cell = document.createElement("td");
    cell.textContent = value;
    return cell;
}

function createRiskCell(highRiskCount, text) {
    const cell = document.createElement("td");
    
    const isHigh = highRiskCount > 0;
    const badgeClass = isHigh ? "alta" : "baja";
    const badgeText = isHigh ? `${highRiskCount} ${text.highRiskBadge}` : text.noHighRisk;

    cell.innerHTML = `<span class="badge ${badgeClass}">${badgeText}</span>`;
    
    return cell;
}
